name: Deploy frontend

on:
  push:
    branches:
      - master

jobs:
  deploy:
    runs-on: self-hosted  
    steps:
      - name: Pull and Restart Docker Containers
        run: |
          cd /home/pi/retrospective/retrospective-app 
          
          git pull
          
          cd ..

          docker compose up -d --build

          docker image prune -f
