name: Unit Tests
on:
  push:
    branches:
      - '**'      
      - '!master'
  workflow_call:  
    outputs:
      test_result:
        value: ${{ jobs.unit-test.result }}

jobs:
  unit-test:
    runs-on: self-hosted
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: 'npm'
      - name: Install dependencies
        run: npm ci
      - name: Run unit tests
        run: npm run test

      - name: Notify 
        if: always()
        uses: appleboy/telegram-action@master
        with:
          to: ${{ secrets.TELEGRAM_CHAT_ID }}
          token: ${{ secrets.TELEGRAM_BOT_TOKEN }}
          socks5: ${{secrets.SOCKS5_PROXY}}
          message: |
            Юнит тесты.
            Статус тестов: ${{ job.status == 'success' && '✅ Успешно' || '❌ Ошибка' }}
            Репозиторий: ${{ github.repository }}
            Ветка: ${{ github.ref_name }}
            Автор: ${{ github.actor }}
            Посмотреть: https://github.com/${{ github.repository }}/actions/runs/${{ github.run_id }}
