name: Unit Tests
on:
  push:
    branches: [ "**" ] 

jobs:
  unit-test:
    runs-on: self-hosted
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: 'npm'
      - run: npm ci
      - run: npm run test

      - name: Notify 
        if: always()
        uses: appleboy/telegram-action@master
        with:
          to: ${{ secrets.TELEGRAM_CHAT_ID }}
          token: ${{ secrets.TELEGRAM_BOT_TOKEN }}
          message: |
            Юнит тесты.
            Статус тестов: ${{ job.status == 'success' && '✅ Успешно' || '❌ Ошибка' }}
            Репозиторий: ${{ github.repository }}
            Ветка: ${{ github.ref_name }}
            Автор: ${{ github.actor }}
            Посмотреть: https://github.com{{ github.repository }}/actions/runs/${{ github.run_id }}
